<?php

namespace Database\Seeders;

use App\Models\PontoTuristico;
use Illuminate\Database\Seeder;

class PontoTuristicoSeeder extends Seeder
{
    public function run(): void
    {
        $pontos = [
            [
                'nome' => 'Cristo Redentor',
                'descricao' => 'Uma das Sete Maravilhas do Mundo Moderno, o Cristo Redentor é um monumento icônico localizado no topo do Morro do Corcovado, com uma vista deslumbrante da cidade do Rio de Janeiro.',
                'descricao_curta' => 'Monumento icônico no Morro do Corcovado com vista panorâmica do Rio.',
                'imagem' => 'https://picsum.photos/seed/cristo/800/600',
                'imagens' => [
                    'https://picsum.photos/seed/cristo-2/800/600',
                    'https://picsum.photos/seed/cristo-3/800/600',
                    'https://picsum.photos/seed/cristo-4/800/600',
                ],
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'categoria' => 'Monumento',
                'avaliacao' => 4.9,
                'horario_funcionamento' => '08:00 - 19:00',
                'preco_entrada' => 89.00,
                'tags' => ['monumento', 'vista panorâmica', 'patrimônio'],
                'visualizacoes' => 15420,
                'curtidas' => 892,
                'publicado_em' => now()->subDays(120),
            ],
            [
                'nome' => 'Parque Ibirapuera',
                'descricao' => 'O principal parque urbano de São Paulo, com lagos, museus, áreas verdes e pistas para caminhada. Ideal para lazer e contato com a natureza.',
                'descricao_curta' => 'Principal parque urbano de SP com lagos e museus.',
                'imagem' => 'https://picsum.photos/seed/ibirapuera/800/600',
                'imagens' => [
                    'https://picsum.photos/seed/ibirapuera-2/800/600',
                    'https://picsum.photos/seed/ibirapuera-3/800/600',
                    'https://picsum.photos/seed/ibirapuera-4/800/600',
                    'https://picsum.photos/seed/ibirapuera-5/800/600',
                ],
                'cidade' => 'São Paulo',
                'estado' => 'SP',
                'categoria' => 'Parque',
                'avaliacao' => 4.7,
                'horario_funcionamento' => '05:00 - 22:00',
                'preco_entrada' => null,
                'tags' => ['parque', 'natureza', 'lazer'],
                'visualizacoes' => 12350,
                'curtidas' => 745,
                'publicado_em' => now()->subDays(115),
            ],
            [
                'nome' => 'Pelourinho',
                'descricao' => 'Centro histórico de Salvador, repleto de casarões coloridos, igrejas barrocas, museus e apresentações culturais. Patrimônio Mundial pela UNESCO.',
                'descricao_curta' => 'Centro histórico colorido com cultura e música baiana.',
                'imagem' => 'https://picsum.photos/seed/pelourinho/800/600',
                'imagens' => [
                    'https://picsum.photos/seed/pelourinho-2/800/600',
                    'https://picsum.photos/seed/pelourinho-3/800/600',
                ],
                'cidade' => 'Salvador',
                'estado' => 'BA',
                'categoria' => 'Cultural',
                'avaliacao' => 4.6,
                'horario_funcionamento' => '24 horas',
                'preco_entrada' => null,
                'tags' => ['história', 'cultura', 'música'],
                'visualizacoes' => 9870,
                'curtidas' => 623,
                'publicado_em' => now()->subDays(110),
            ],
            [
                'nome' => 'Igreja de São Francisco de Assis',
                'descricao' => 'Igreja barroca em Ouro Preto, famosa por sua arquitetura deslumbrante e obras de Aleijadinho. Um dos maiores tesouros do barroco brasileiro.',
                'descricao_curta' => 'Igreja barroca com obras de Aleijadinho em Ouro Preto.',
                'imagem' => 'https://picsum.photos/seed/saofrancisco/800/600',
                'cidade' => 'Ouro Preto',
                'estado' => 'MG',
                'categoria' => 'Igreja',
                'avaliacao' => 4.5,
                'horario_funcionamento' => '09:00 - 17:00',
                'preco_entrada' => 12.00,
                'tags' => ['barroco', 'Aleijadinho', 'história'],
                'visualizacoes' => 6540,
                'curtidas' => 412,
                'publicado_em' => now()->subDays(105),
            ],
            [
                'nome' => 'Praia do Forte',
                'descricao' => 'Praia paradisíaca no litoral norte da Bahia, com águas cristalinas, piscinas naturais e o Projeto Tamar. Perfeita para famílias e mergulho.',
                'descricao_curta' => 'Praia paradisíaca com piscinas naturais e Projeto Tamar.',
                'imagem' => 'https://picsum.photos/seed/praiadoforte/800/600',
                'cidade' => 'Mata de São João',
                'estado' => 'BA',
                'categoria' => 'Praia',
                'avaliacao' => 4.4,
                'horario_funcionamento' => '24 horas',
                'preco_entrada' => null,
                'tags' => ['praia', 'tamar', 'natureza'],
                'visualizacoes' => 8760,
                'curtidas' => 534,
                'publicado_em' => now()->subDays(100),
            ],
            [
                'nome' => 'Parque Nacional da Tijuca',
                'descricao' => 'Maior floresta urbana do mundo, com trilhas, cachoeiras e muita biodiversidade. Abriga o Pico da Tijuca e a Vista Chinesa.',
                'descricao_curta' => 'Maior floresta urbana do mundo com trilhas e cachoeiras.',
                'imagem' => 'https://picsum.photos/seed/tijuca/800/600',
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'categoria' => 'Natural',
                'avaliacao' => 4.3,
                'horario_funcionamento' => '06:00 - 18:00',
                'preco_entrada' => null,
                'tags' => ['trilha', 'natureza', 'floresta'],
                'visualizacoes' => 5430,
                'curtidas' => 387,
                'publicado_em' => now()->subDays(95),
            ],
            [
                'nome' => 'Mercado Central de Belo Horizonte',
                'descricao' => 'Mercado tradicional com mais de 400 lojas, bares e restaurantes. Imperdível para provar a culinária mineira e comprar artesanato.',
                'descricao_curta' => 'Mercado tradicional com culinária mineira e artesanato.',
                'imagem' => 'https://picsum.photos/seed/mercadocentral/800/600',
                'cidade' => 'Belo Horizonte',
                'estado' => 'MG',
                'categoria' => 'Gastronômico',
                'avaliacao' => 4.2,
                'horario_funcionamento' => '07:00 - 18:00',
                'preco_entrada' => null,
                'tags' => ['gastronomia', 'artesanato', 'cultura'],
                'visualizacoes' => 7890,
                'curtidas' => 456,
                'publicado_em' => now()->subDays(90),
            ],
            [
                'nome' => 'Museu do Ipiranga',
                'descricao' => 'Museu histórico que conta a história do Brasil, localizado no Parque da Independência. Possui um acervo riquíssimo e arquitetura imponente.',
                'descricao_curta' => 'Museu histórico com acervo sobre a história do Brasil.',
                'imagem' => 'https://picsum.photos/seed/ipiranga/800/600',
                'cidade' => 'São Paulo',
                'estado' => 'SP',
                'categoria' => 'Museu',
                'avaliacao' => 4.1,
                'horario_funcionamento' => '10:00 - 17:00',
                'preco_entrada' => 20.00,
                'tags' => ['museu', 'história', 'independência'],
                'visualizacoes' => 4560,
                'curtidas' => 298,
                'publicado_em' => now()->subDays(85),
            ],
            [
                'nome' => 'Catedral Metropolitana de Curitiba',
                'descricao' => 'Catedral histórica localizada no centro de Curitiba, com arquitetura neogótica e belos vitrais. Ponto de referência na Praça Tiradentes.',
                'descricao_curta' => 'Catedral neogótica com belos vitrais no centro de Curitiba.',
                'imagem' => 'https://picsum.photos/seed/catedralctba/800/600',
                'cidade' => 'Curitiba',
                'estado' => 'PR',
                'categoria' => 'Igreja',
                'avaliacao' => 4.0,
                'horario_funcionamento' => '07:00 - 19:00',
                'preco_entrada' => null,
                'tags' => ['igreja', 'arquitetura', 'vitrais'],
                'visualizacoes' => 3450,
                'curtidas' => 234,
                'publicado_em' => now()->subDays(80),
            ],
            [
                'nome' => 'Jardim Botânico do Rio de Janeiro',
                'descricao' => 'Um dos mais importantes jardins botânicos do mundo, com diversas espécies de plantas, estufas e o famoso jardim francês. Fundado em 1808.',
                'descricao_curta' => 'Jardim botânico centenário com espécies raras e jardim francês.',
                'imagem' => 'https://picsum.photos/seed/jardimbotanico/800/600',
                'imagens' => [
                    'https://picsum.photos/seed/jardimbotanico-2/800/600',
                    'https://picsum.photos/seed/jardimbotanico-3/800/600',
                ],
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'categoria' => 'Parque',
                'avaliacao' => 4.8,
                'horario_funcionamento' => '06:00 - 17:00',
                'preco_entrada' => 15.00,
                'tags' => ['natureza', 'jardim', 'plantas'],
                'visualizacoes' => 9870,
                'curtidas' => 678,
                'publicado_em' => now()->subDays(75),
            ],
            [
                'nome' => 'Teatro Amazonas',
                'descricao' => 'Teatro histórico em Manaus, símbolo da Belle Époque brasileira. Construído no ciclo da borracha, com arquitetura europeia e acústica impecável.',
                'descricao_curta' => 'Teatro histórico da Belle Époque no coração da Amazônia.',
                'imagem' => 'https://picsum.photos/seed/teatroamazonas/800/600',
                'cidade' => 'Manaus',
                'estado' => 'AM',
                'categoria' => 'Cultural',
                'avaliacao' => 4.6,
                'horario_funcionamento' => '09:00 - 17:00',
                'preco_entrada' => 30.00,
                'tags' => ['teatro', 'história', 'arquitetura'],
                'visualizacoes' => 6540,
                'curtidas' => 445,
                'publicado_em' => now()->subDays(70),
            ],
            [
                'nome' => 'Beto Carrero World',
                'descricao' => 'Maior parque temático da América Latina, com montanhas-russas, shows e diversas atrações para todas as idades. Localizado em Penha, SC.',
                'descricao_curta' => 'Maior parque temático da América Latina com atrações radicais.',
                'imagem' => 'https://picsum.photos/seed/betocarrero/800/600',
                'imagens' => [
                    'https://picsum.photos/seed/betocarrero-2/800/600',
                    'https://picsum.photos/seed/betocarrero-3/800/600',
                    'https://picsum.photos/seed/betocarrero-4/800/600',
                ],
                'cidade' => 'Penha',
                'estado' => 'SC',
                'categoria' => 'Aventura',
                'avaliacao' => 4.5,
                'horario_funcionamento' => '09:00 - 18:00',
                'preco_entrada' => 280.00,
                'tags' => ['parque', 'diversão', 'aventura'],
                'visualizacoes' => 11230,
                'curtidas' => 723,
                'publicado_em' => now()->subDays(65),
            ],
            [
                'nome' => 'Ouro Preto',
                'descricao' => 'Cidade histórica mineira, Patrimônio Mundial pela UNESCO. Famosas por suas igrejas barrocas, ladeiras de paralelepípedos e museus.',
                'descricao_curta' => 'Cidade histórica mineira, Patrimônio Mundial com igrejas barrocas.',
                'imagem' => 'https://picsum.photos/seed/ouropreto/800/600',
                'cidade' => 'Ouro Preto',
                'estado' => 'MG',
                'categoria' => 'Histórico',
                'avaliacao' => 4.7,
                'horario_funcionamento' => '24 horas',
                'preco_entrada' => null,
                'tags' => ['história', 'barroco', 'colonial'],
                'visualizacoes' => 8760,
                'curtidas' => 567,
                'publicado_em' => now()->subDays(60),
            ],
            [
                'nome' => 'Fernando de Noronha',
                'descricao' => 'Arquipélago paradisíaco com praias exuberantes, águas cristalinas e rica vida marinha. Um dos destinos mais desejados do Brasil.',
                'descricao_curta' => 'Arquipélago paradisíaco com as praias mais bonitas do Brasil.',
                'imagem' => 'https://picsum.photos/seed/noronha/800/600',
                'imagens' => [
                    'https://picsum.photos/seed/noronha-2/800/600',
                    'https://picsum.photos/seed/noronha-3/800/600',
                    'https://picsum.photos/seed/noronha-4/800/600',
                    'https://picsum.photos/seed/noronha-5/800/600',
                    'https://picsum.photos/seed/noronha-6/800/600',
                ],
                'cidade' => 'Fernando de Noronha',
                'estado' => 'PE',
                'categoria' => 'Praia',
                'avaliacao' => 4.9,
                'horario_funcionamento' => '24 horas',
                'preco_entrada' => 92.00,
                'tags' => ['praia', 'mergulho', 'natureza'],
                'visualizacoes' => 18760,
                'curtidas' => 1234,
                'publicado_em' => now()->subDays(55),
            ],
            [
                'nome' => 'Bonito',
                'descricao' => 'Destino de ecoturismo no Mato Grosso do Sul, famoso por suas grutas, rios de águas cristalinas, cavernas e cachoeiras. Paraíso para mergulho.',
                'descricao_curta' => 'Paraíso do ecoturismo com rios cristalinos e grutas.',
                'imagem' => 'https://picsum.photos/seed/bonito/800/600',
                'cidade' => 'Bonito',
                'estado' => 'MS',
                'categoria' => 'Natural',
                'avaliacao' => 4.8,
                'horario_funcionamento' => '07:00 - 18:00',
                'preco_entrada' => 50.00,
                'tags' => ['ecoturismo', 'mergulho', 'natureza'],
                'visualizacoes' => 13450,
                'curtidas' => 890,
                'publicado_em' => now()->subDays(50),
            ],
        ];

        foreach ($pontos as $ponto) {
            PontoTuristico::create($ponto);
        }
    }
}
